"""
test_gguf2vk.py — no pytest dependency, plain assert-based runner.

Run: python3 test_gguf2vk.py [path/to/extra_test_model.gguf ...]

Test tiers:
  1. Legacy dequant — hand-computed expected values (not generated by the
     function under test), catches real sign/shift/byte-order bugs.
  2. Requant + relayout round-trip — programmatic, checks losslessness
     (relayout) and bounded error (requant, since int8 quantization is lossy
     by design).
  3. K-quant (Q4_K/Q6_K) structural — runs against whatever real GGUF tensors
     are available, checks no crash / finite values / right element count.
     Does NOT prove the math is correct, only that it doesn't fall over.
  4. Integration — full convert.py pipeline against any uploaded .gguf files
     found, end to end, checking the output file is written and openable.
"""

import glob
import struct
import sys
import numpy as np

import dequant
import dequant_ref
import requant
import requant_ref
import relayout
import relayout_ref
import native_relayout
import verify_native
from gguf_reader import parse_gguf
from ggml_types import tensor_byte_size, tensor_element_count

PASS = []
FAIL = []


def check(name, cond, detail=""):
    if cond:
        PASS.append(name)
        print(f"  PASS  {name}")
    else:
        FAIL.append(name)
        print(f"  FAIL  {name}  {detail}")


def close(a, b, tol=1e-3):
    return abs(a - b) < tol


# ---------- Tier 1: legacy dequant, hand-computed expected values ----------

def test_q4_0():
    qs = bytearray(16)
    qs[0] = 0x00   # low=0 high=0 -> -8, -8
    qs[1] = 0xFF   # low=15 high=15 -> 7, 7
    for i in range(2, 16):
        qs[i] = 0x88  # low=8 high=8 -> 0, 0
    block = np.float16(1.0).tobytes() + bytes(qs)
    y = dequant.dequant_q4_0(block, 32)
    check("Q4_0 nibble 0x00", close(y[0], -8) and close(y[16], -8))
    check("Q4_0 nibble 0xFF", close(y[1], 7) and close(y[17], 7))
    check("Q4_0 nibble 0x88 (mid)", close(y[2], 0) and close(y[18], 0))


def test_q4_1():
    qs = bytearray(16)
    qs[0] = 0x00
    qs[1] = 0xFF
    block = np.float16(1.0).tobytes() + np.float16(0.0).tobytes() + bytes(qs)
    y = dequant.dequant_q4_1(block, 32)
    check("Q4_1 nibble 0x00 (no offset)", close(y[0], 0) and close(y[16], 0))
    check("Q4_1 nibble 0xFF (no offset)", close(y[1], 15) and close(y[17], 15))


def test_q8_0():
    vals = [0, 1, -1, 127, -127] + [0] * 27
    block = np.float16(2.0).tobytes() + np.array(vals, dtype=np.int8).tobytes()
    y = dequant.dequant_q8_0(block, 32)
    check("Q8_0 scale*value", close(y[0], 0) and close(y[1], 2) and close(y[2], -2)
          and close(y[3], 254) and close(y[4], -254))


def test_q5_0():
    qs = bytearray(16)
    qs[0] = 0x00
    qs[1] = 0xFF
    qh_zero = struct.pack("<I", 0)
    block = np.float16(1.0).tobytes() + qh_zero + bytes(qs)
    y = dequant.dequant_q5_0(block, 32)
    check("Q5_0 qh=0, nibble 0x00 (-16 offset)", close(y[0], -16) and close(y[16], -16))
    check("Q5_0 qh=0, nibble 0xFF", close(y[1], -1) and close(y[17], -1))

    # now flip qh bit 0 -> high bit of x0 (j=0) set -> value becomes 0 instead of -16
    qh_bit0 = struct.pack("<I", 1)
    block2 = np.float16(1.0).tobytes() + qh_bit0 + bytes(qs)
    y2 = dequant.dequant_q5_0(block2, 32)
    check("Q5_0 qh bit0 set flips high bit of x0", close(y2[0], 0), f"got {y2[0]}")


def test_q5_1():
    qs = bytearray(16)
    qs[0] = 0x00
    qs[1] = 0xFF
    qh_zero = struct.pack("<I", 0)
    block = np.float16(1.0).tobytes() + np.float16(0.0).tobytes() + qh_zero + bytes(qs)
    y = dequant.dequant_q5_1(block, 32)
    check("Q5_1 qh=0, nibble 0x00 (no offset)", close(y[0], 0) and close(y[16], 0))
    check("Q5_1 qh=0, nibble 0xFF", close(y[1], 15) and close(y[17], 15))


def test_f32_f16():
    x = np.array([1.5, -2.25, 0.0, 3.0], dtype=np.float32)
    y = dequant.dequant_f32(x.tobytes(), 4)
    check("F32 passthrough", np.allclose(x, y))

    xh = x.astype(np.float16)
    yh = dequant.dequant_f16(xh.tobytes(), 4)
    check("F16 upcast", np.allclose(x, yh, atol=1e-2))


# ---------- Tier 1b: vectorized dequant diff-tested against the pre-vectorization oracle ----------

def _rand_bytes(rng, n):
    return rng.integers(0, 256, size=n, dtype=np.uint8).tobytes()


def _rand_fp16_bytes(rng, n_values):
    vals = rng.uniform(-4, 4, size=n_values).astype(np.float16)
    return vals.tobytes()


def test_diff_legacy_vs_oracle():
    rng = np.random.default_rng(42)
    n_blocks = 17  # deliberately not a round number

    specs = [
        ("Q4_0", dequant.dequant_q4_0, dequant_ref._slow_dequant_q4_0, 18, [(0, 2, "fp16")]),
        ("Q4_1", dequant.dequant_q4_1, dequant_ref._slow_dequant_q4_1, 20, [(0, 2, "fp16"), (2, 4, "fp16")]),
        ("Q5_0", dequant.dequant_q5_0, dequant_ref._slow_dequant_q5_0, 22, [(0, 2, "fp16")]),
        ("Q5_1", dequant.dequant_q5_1, dequant_ref._slow_dequant_q5_1, 24, [(0, 2, "fp16"), (2, 4, "fp16")]),
        ("Q8_0", dequant.dequant_q8_0, dequant_ref._slow_dequant_q8_0, 34, [(0, 2, "fp16")]),
    ]
    for name, fast_fn, slow_fn, type_size, fp16_fields in specs:
        blocks = bytearray(_rand_bytes(rng, n_blocks * type_size))
        for i in range(n_blocks):
            base = i * type_size
            for (off, end, _) in fp16_fields:
                blocks[base + off:base + end] = _rand_fp16_bytes(rng, 1)
        data = bytes(blocks)
        n_elements = n_blocks * 32
        fast = fast_fn(data, n_elements)
        slow = slow_fn(data, n_elements)
        check(f"{name} vectorized matches oracle", np.allclose(fast, slow, equal_nan=True),
              f"max diff {np.max(np.abs(fast - slow))}")


def test_diff_kquant_vs_oracle():
    rng = np.random.default_rng(43)
    n_blocks = 3

    def make_q4k_block():
        d = _rand_fp16_bytes(rng, 1)
        dmin = _rand_fp16_bytes(rng, 1)
        scales = _rand_bytes(rng, 12)
        qs = _rand_bytes(rng, 128)
        return d + dmin + scales + qs

    def make_q6k_block():
        ql = _rand_bytes(rng, 128)
        qh = _rand_bytes(rng, 64)
        scales = rng.integers(-127, 127, size=16, dtype=np.int8).tobytes()
        d = _rand_fp16_bytes(rng, 1)
        return ql + qh + scales + d

    data_q4k = b"".join(make_q4k_block() for _ in range(n_blocks))
    n_elements = n_blocks * 256
    fast = dequant.dequant_q4_k(data_q4k, n_elements)
    slow = dequant_ref._slow_dequant_q4_k(data_q4k, n_elements)
    check("Q4_K vectorized matches oracle", np.allclose(fast, slow, equal_nan=True),
          f"max diff {np.max(np.abs(fast - slow))}")

    data_q6k = b"".join(make_q6k_block() for _ in range(n_blocks))
    fast = dequant.dequant_q6_k(data_q6k, n_elements)
    slow = dequant_ref._slow_dequant_q6_k(data_q6k, n_elements)
    check("Q6_K vectorized matches oracle", np.allclose(fast, slow, equal_nan=True),
          f"max diff {np.max(np.abs(fast - slow))}")


def test_q3k_scale_packing_self_consistency():
    """No independent oracle exists for Q3_K (new format), so this checks the
    unpack function against an algebraically-derived inverse (pack_q3k_scales)
    instead — catches real bit-manipulation bugs even without ground truth."""
    rng = np.random.default_rng(7)
    n_blocks = 50
    original = rng.integers(-32, 32, size=(n_blocks, 16)).astype(np.int32)
    packed = dequant.pack_q3k_scales(original)
    recovered = dequant.unpack_q3k_scales(packed)
    check("Q3_K scale pack/unpack round-trip", np.array_equal(original, recovered),
          f"mismatch count: {np.sum(original != recovered)}")


# ---------- Tier 2: requant + relayout round-trip ----------

def test_requant_roundtrip():
    rng = np.random.default_rng(0)
    x = rng.uniform(-5, 5, size=320).astype(np.float32)
    err = requant.roundtrip_error(x, "q8_0")
    check("Q8_0 requant round-trip error bounded", err < 0.1, f"max err = {err}")

    err4 = requant.roundtrip_error(x, "q4_0")
    # 4-bit quant is much coarser — bound generously (range ~10, 15 levels)
    check("Q4_0 requant round-trip error bounded", err4 < 1.0, f"max err = {err4}")


def test_relayout_roundtrip():
    rng = np.random.default_rng(1)
    matrix = rng.uniform(-1, 1, size=(37, 19)).astype(np.float32)  # deliberately not tile-aligned
    tiled = relayout.to_tiled(matrix, 8, 4)
    back = relayout.from_tiled(tiled, 37, 19, 8, 4)
    check("Relayout round-trip lossless incl. ragged edges", np.allclose(matrix, back))


def test_requant_vs_oracle():
    rng = np.random.default_rng(11)
    x = rng.uniform(-5, 5, size=320).astype(np.float32)
    fast = requant.quantize_q8_0(x)
    slow = requant_ref._slow_quantize_q8_0(x)
    check("Vectorized requant matches oracle bytes", fast == slow)


def test_relayout_vs_oracle():
    rng = np.random.default_rng(12)
    matrix = rng.uniform(-1, 1, size=(37, 19)).astype(np.float32)
    fast = relayout.to_tiled(matrix, 8, 4)
    slow = relayout_ref._slow_to_tiled(matrix, 8, 4)
    check("Vectorized relayout matches oracle", np.allclose(fast, slow))


def test_native_relayout_roundtrip():
    rng = np.random.default_rng(20)
    # deliberately ragged: 13 rows, 7 blocks/row, type_size 18 (Q4_0-shaped), tile 4x3
    nrows, blocks_per_row, type_size = 13, 7, 18
    raw = rng.integers(0, 256, size=nrows * blocks_per_row * type_size, dtype=np.uint8).tobytes()
    tiled = native_relayout.to_tiled_native(raw, nrows, blocks_per_row, type_size, 4, 3)
    back = native_relayout.from_tiled_native(tiled, nrows, blocks_per_row, type_size, 4, 3)
    check("Native block relayout round-trip is byte-exact (no quant error possible here)",
          back == raw)


def test_native_relayout_zero_padding_is_safe():
    """Confirms an all-zero padding block decodes to exactly zero for a
    representative sample of implemented formats — the assumption
    native_relayout.py's padding relies on."""
    import struct as _struct
    cases = [
        ("Q4_0", dequant.dequant_q4_0, 18, 32),
        ("Q5_0", dequant.dequant_q5_0, 22, 32),
        ("Q8_0", dequant.dequant_q8_0, 34, 32),
        ("Q4_K", dequant.dequant_q4_k, 144, 256),
        ("Q6_K", dequant.dequant_q6_k, 210, 256),
    ]
    for name, fn, type_size, n_elem in cases:
        zero_block = bytes(type_size)
        y = fn(zero_block, n_elem)
        check(f"{name} zero block decodes to all zeros", np.all(y == 0), f"nonzero values: {y[y!=0][:5]}")


# ---------- Tier 4b: native mode integration (no quant error possible; must match originals exactly) ----------

def test_verify_native_script(gguf_paths):
    """Runs the actual verify_native.py end-to-end against real converted
    files — the same script the user runs by hand, not a reimplementation
    of its logic."""
    import convert
    import tempfile
    import os
    for path in gguf_paths:
        out = tempfile.mktemp(suffix=".gguf")
        try:
            rc = convert.run(path, out, tile_rows=32, tile_cols=8, fmt="native", force=True)
            if rc != 0:
                check(f"verify_native script: {path}", False, "conversion itself failed")
                continue
            ok = verify_native.verify(path, out)
            check(f"verify_native script: {path}", ok)
        except Exception as e:
            check(f"verify_native script: {path}", False, str(e))
        finally:
            if os.path.exists(out):
                os.remove(out)


def test_native_integration(gguf_paths):
    """For every 2-D tensor in the provided files, native-relayout its raw
    blocks, then reverse the relayout and confirm we get back byte-identical
    original bytes. This is a much stronger check than the q8_0/q4_0
    integration test (Tier 4) since native mode has zero quantization error
    — any mismatch here is a real bug, not rounding."""
    from ggml_types import GGML_TYPES, tensor_byte_size
    checked_any = False
    for path in gguf_paths:
        try:
            g = parse_gguf(path)
        except Exception as e:
            check(f"parse {path}", False, str(e))
            continue
        for t in g.tensors:
            if len(t.shape) != 2 or t.ggml_type not in GGML_TYPES:
                continue
            info = GGML_TYPES[t.ggml_type]
            ncols, nrows = t.shape[0], t.shape[1]
            if ncols % info.block_size != 0:
                continue
            blocks_per_row = ncols // info.block_size
            byte_size = tensor_byte_size(t.shape, t.ggml_type)
            start = g.tensor_data_start + t.offset
            raw = g.raw[start:start + byte_size]

            tiled = native_relayout.to_tiled_native(raw, nrows, blocks_per_row, info.type_size, 32, 2)
            back = native_relayout.from_tiled_native(tiled, nrows, blocks_per_row, info.type_size, 32, 2)
            check(f"native round-trip byte-exact: {t.name} ({info.name}) in {path}", back == raw)
            checked_any = True
    if not checked_any:
        print("  (no eligible 2-D tensors found — tier 4b skipped, not failed)")


# ---------- Tier 3: K-quant structural (needs a real file with Q4_K/Q6_K tensors) ----------

def test_kquant_structural(gguf_paths):
    found_q4k = found_q6k = False
    for path in gguf_paths:
        try:
            g = parse_gguf(path)
        except Exception as e:
            check(f"parse {path}", False, str(e))
            continue
        for t in g.tensors:
            if t.ggml_type not in (12, 14):
                continue
            n_elements = tensor_element_count(t.shape)
            byte_size = tensor_byte_size(t.shape, t.ggml_type)
            start = g.tensor_data_start + t.offset
            raw = g.raw[start:start + byte_size]
            try:
                y = dequant.dequantize(t.ggml_type, raw, n_elements)
                ok = y.shape[0] == n_elements and np.all(np.isfinite(y))
                label = "Q4_K" if t.ggml_type == 12 else "Q6_K"
                check(f"{label} structural: {t.name} in {path}", ok,
                      f"shape mismatch or non-finite values")
                if t.ggml_type == 12:
                    found_q4k = True
                else:
                    found_q6k = True
            except Exception as e:
                check(f"K-quant dequant {t.name}", False, str(e))
    if not (found_q4k or found_q6k):
        print("  (no Q4_K/Q6_K tensors found in provided files — tier 3 skipped, not failed)")


# ---------- Tier 4: integration, full pipeline on real files ----------

def test_integration(gguf_paths):
    import convert
    import tempfile
    import os
    for path in gguf_paths:
        for fmt in ["q8_0", "q4_0", "native"]:
            out = tempfile.mktemp(suffix=".gguf")
            try:
                rc = convert.run(path, out, tile_rows=32, tile_cols=8, fmt=fmt, force=True)
                ok = rc == 0 and os.path.exists(out) and os.path.getsize(out) > 0
                check(f"integration convert [{fmt}]: {path}", ok)
            except Exception as e:
                check(f"integration convert [{fmt}]: {path}", False, str(e))
            finally:
                if os.path.exists(out):
                    os.remove(out)


if __name__ == "__main__":
    print("=== Tier 1: legacy dequant (hand-verified) ===")
    test_q4_0()
    test_q4_1()
    test_q8_0()
    test_q5_0()
    test_q5_1()
    test_f32_f16()

    print("\n=== Tier 1b: vectorized dequant vs pre-vectorization oracle ===")
    test_diff_legacy_vs_oracle()
    test_diff_kquant_vs_oracle()
    test_q3k_scale_packing_self_consistency()

    print("\n=== Tier 2: requant + relayout round-trip ===")
    test_requant_roundtrip()
    test_relayout_roundtrip()
    test_requant_vs_oracle()
    test_relayout_vs_oracle()
    test_native_relayout_roundtrip()
    test_native_relayout_zero_padding_is_safe()

    extra_paths = sys.argv[1:]
    default_paths = glob.glob("/mnt/user-data/uploads/*.gguf")
    gguf_paths = extra_paths or default_paths

    print(f"\n=== Tier 3: K-quant structural ({len(gguf_paths)} file(s) found) ===")
    test_kquant_structural(gguf_paths)

    print(f"\n=== Tier 4: integration ({len(gguf_paths)} file(s)) ===")
    test_integration(gguf_paths)

    print(f"\n=== Tier 4b: native mode round-trip ({len(gguf_paths)} file(s)) ===")
    test_native_integration(gguf_paths)
    test_verify_native_script(gguf_paths)

    print(f"\n{len(PASS)} passed, {len(FAIL)} failed.")
    sys.exit(1 if FAIL else 0)
